### PR TITLE
Change 'float' to 'double' (plus small clean up for RatingTest)

### PR DESCRIPTION
**Pull request by boxspah**

### CODE REVIEW

**Comment by csclover420** [comment]
why did we change from float to double?

**Comment by noahsub** [comment]
double can hold more digits than float, double stores up to 64 bits

**Comment by dungwoong** [comment]
because double is how java typically stores numbers, so we don't need to write 10.0f, for example, we can just write 10

**Comment by boxspah** [comment]
`double` also gives us more floating-point precision, which will improve the average score calculation for courses.

**Pull request merged**
